### ISSUE TITLE
Processing speed and memory

### ISSUE THREAD

**Issue by rezaparaanczi** [SBC-Utrecht/pytom-match-pick#101]
Hello,

Thanks for the nice tutorial. I have been testing this on my data and it works great for ribosomes with a 40 Angstrom filter on tomograms with 21.12 A/pix pixel size (K3 camera, bin 8). I'm looking at another target and decided to do higher resolution template matching with the template at 22 Angstrom low pass filter, and tomogram pixel size of 10.56 A/pix (bin 4), sampling is 3 degrees. With these new setting I can only run pytom on gpus with 80GB of memory, as it's taking 42GB of memory during the run which is slightly more than the next grade gpus with 40GB of memory. I was wondering if I'm missing something, because according to the tutorial a 1080 Ti gpu has enough memory for this job and that only has ~10 GB of memory. That's the memory issue I wanted to raise. I also wanted to raise a speed issue, because with 4 A100 gpus it takes 28 hours for one tomogram. I would appreciate any suggestions. Here is an example command I'm running:
pytom_match_template.py -t templates/template.mrc -m templates/mask_10.56Apix.mrc -v paceview12_ts_001.mrc.2000.wbp.yz.tapered.rec -d results_RP_3deg_weightwhite2/ -a rawtlt/paceview12_ts_001.mrc.rawtlt --angular-search 3.00 --voxel-size 10.56 --low-pass 22 -g 0 1 2 3 --per-tilt-weighting --spectral-whitening

**Comment by McHaillet** [comment]
Hi! Nice to hear its working!

The memory issue can be easily solved by splitting your tomogram into smaller patches, see the `-s`, `--volume-split` option for [pytom_match_template.py ](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/wiki/template-matching). With the memory use you are indicating `-s 2 1 1` would already be sufficient, this would split the tomo once along the x-axis. If that is still too large, you could try `-s 3 1 1` or `-s 2 2 1`. 

> I also wanted to raise a speed issue, because with 4 A100 gpus it takes 28 hours for one tomogram.

That seems about right for such a volume/angular-search combination. Although on our cluster a tomo of size 928x960x500 with 3.00 search on 4 GPU's takes ~10h. I guess because of the K3 your tomos are slightly larger, but that does seem a factor 2 slower. In general though, the exhaustive search does take a long time on such dimensions. 

Some suggestions:
- You can look at the `--search-x`, `--search-y`, `--search-z` options to crop the search volume. Often along the z-axis there are some empty regions above/below the ice.
- I would suggest you try to run the 7.00 degrees search first with this template/tomo combination, usually that already gives a good indication about whether you can localize your template. If you subsequently need optimal sensitivity you can increase the angular search. 

Best wishes

**Comment by rezaparaanczi** [comment]
Thank you so much. Very helpful.

**Comment by rezaparaanczi** [comment]
Are the coordinates for search-xyz similar to imod coordinates? Thanks.

**Comment by McHaillet** [comment]
I dont know how you mean exactly, but Ill give an example:

Let say your 4x binned tomogram has 500 pixels along the z-axis. However the ice layers is less thick than that only starts at z-slice 100, and stops at z-slice 400: setting `--search-z 100 400` would properly limit it. 

These slices would correspond to what you see in 3dmod for example.

**Comment by rezaparaanczi** [comment]
Sorry for not being clear. I mean is the origin of the coordinates similar to imod which is the bottom lower left corner? Thanks.

**Comment by McHaillet** [comment]
If you select your cutoffs based on the IMOD viewer and know there how they relate to the origin, you can plug them in to template matching and it will work. Vice versa if you have extracted particle coordinates and you would visualize them in IMOD they will be in the correct place.

Whether the bottom-left corner is the origin is a display convention. Napari for example displays the top-left corner as the origin.

**Comment by McHaillet** [comment]
Hi!
I did some digging and it turns out the cupy installation can result in quite some speed difference. On our system we get an almost 2-fold speed increase if we build cupy against local cuda installation, quite significant for the 28 hours you mention. 

I updated the install instructions in the README to reflect building cupy as the recommended way. I you want better performance I would recommend to reinstall pytom in a clean environment (or ask your system administrator to reinstall). If you do so, please also update to the latest version from the github repo (0.3.4)

**Comment by rezaparaanczi** [comment]
OK thank you so much, This is really helpful.

**Comment by McHaillet** [comment]
I will close this issue as I updated the README for the cupy installation, and secondly put update the docs about volume splitting on another to-do list.
