### ISSUE TITLE
including mask during template matching to reduce the search space

### ISSUE THREAD

**Issue by McHaillet** [SBC-Utrecht/pytom-match-pick#54]
Some people asked if the search space could be constraint during the actual template matching instead of during candidate extraction, to improve runtimes in tomograms were only a small section is of interest.

The most feasible suggestion seems to check if a patch of the tomogram (as split with the `-s` option in `pytom_match_template.py`) has values of 1 in its mask patch. If the volume is not split into patches (i.e. just one big patch), there will always be a positive mask section and therefore the search wont be restrained. However, if the volume is actually split by the user only the patches with positve mask values will have to be calculated.

**Comment by hamid13r** [comment]
I just wanted to add my latest observation to this. I think this is a great idea (I was a little skeptical at first) because this becomes important with larger tomograms that need to be split. (I also just started running pyTOM on 4 GPUs) so if this is a cellular lamella there is a good chance it can be split into 12-24 patches and ~half of them are empty.  Obviously, skipping empty patches can speed pyTOM up significantly.
